<?php

namespace SqlSrvBundle\Repository;

/**
 * ItemSubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemSubFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
