<?php

namespace SqlSrvBundle\Repository;

/**
 * ItemFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
