<?php

namespace SqlSrvBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findItems()
    {
        $it = $this->createQueryBuilder('i')
            ->select('i.id, i.caption, i.descom')
            ->getQuery();

        return $it->getResult();
    }

    public function findtest($id)
    {
        $d = $this->createQueryBuilder('i')
            ->select('i.id, i.caption, i.descom')
            ->where("i.id > :id")
            ->setParameter('id',$id)
            ->getQuery();
        return $d->getResult();
    }
}
