<?php

namespace SqlSrvBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaleDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleDocumentRepository extends EntityRepository
{
//    public function findSafeDoc()
//    {
//        return  $q = $this->createQueryBuilder("s")
//            ->select('s.documentValidDate,s.deliveryDate,s.documentDate,s.documentNumber')
//            ->where("s.id = 93623F70-991B-4388-B98E-00028B65094F")
//            ->setMaxResults(5)
//            ->getQuery()
//            ->getResult();
//    }
}
