<?php

namespace SqlSrvBundle\Repository;

/**
 * SaleDocumentLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleDocumentLineRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findDetails()
//    {
//        $d = $this->createQueryBuilder('dd')
//            ->select("dd.documentId","dd.description","dd.quantity")
//            ->where()
//    }

}
