planning_planning:
    resource: "@PlanningBundle/Controller/Main/PlanningController.php"
    type:     annotation

planning_planning:
    resource: "@PlanningBundle/Controller/Main/PlanningController.php"
    type:     annotation

sql_srv:
    resource: "@SqlSrvBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin