easy_admin:
    entities:
        Actor:
            class: PlanningBundle\Entity\Main\Actor
            list:
                title: "Actors Workshops"
                fields:
                    - enabled
                    - name
                    - task

            form:
                fields:
                    - { type: 'group' , label: 'Information', css_class: 'col-sm-6', icon: 'user' }
#                    - { property: 'id', css_class: 'id_actor' }
                    - name
                    - enabled
                    - { type: 'group', label: 'Tasks', css_class: 'col-sm-6', icon: 'tasks' }
                    - task

            new:
                title:  'Ajouter un nouvel acteur'
                fileds:
                    - task
                form_options: { validation_groups: ['Default', 'Actor'] }


            edit:
                title:  "Modifier l'Acteur"
                form_options: { validation_groups: ['Default', 'Actor'] }

            show:
                title:  "Acteur"
                fileds:
                    - task
                form_options: { validation_groups: ['Default', 'Actor'] }



