easy_admin:
    entities:
        Task:
            class: PlanningBundle\Entity\Main\Task
            form_theme: 'vertical'
            list:
                title: "List of Task"
                fields:
                    - name
                    - actor
                    - position
            form:
                fields:
                    - { type: 'group' , label: 'Information', css_class: 'col-sm-6', icon: 'user' }
                    - name
                    - { type: 'group', label: 'Position', css_class: 'col-sm-6', icon: 'position' }
                    - position

            new:
                title:  'Ajouter une nouvelle tâche'
                form_options: { validation_groups: ['Default', 'Task'] }

            edit:
                title:  "Modifier la tâche"
                fileds:
                    - position
                form_options: { validation_groups: ['Default', 'Task'] }

            show:
                title: "tâche"
                fields:
                    - position
                    - actor

