<?php

namespace PlanningBundle\Repository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActor($id)
    {
        // Création d'une requete personnalisé Query Builder
        $q = $this->createQueryBuilder("a") // Création d'un alias
        ->addSelect("c")
            ->join("a.competence", "c")
            ->groupBy('c.id')
//            ->where('c.id = :id')
//            ->setParameter('id', $id)
        ->getQuery();

        return $q->getResult();
    }
}
