<?php

namespace PlanningBundle\Repository;

/**
 * ItemCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
