<?php

namespace PlanningBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findlastid()
    {
        $d = $this->createQueryBuilder('s')
            ->select('s.id')
            ->orderBy('s.id', 'DESC')
            ->setFirstResult(1)
            ->setMaxResults(1)
            ->getQuery();
        return $d->getSingleResult();
    }
}
