<?php

namespace PlanningBundle\Repository;

/**
 * ListCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
