<?php

namespace PlanningBundle\Repository;

/**
 * MainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainRepository extends \Doctrine\ORM\EntityRepository
{
}
