<?php

namespace PlanningBundle\Repository;

/**
 * PlanningTypeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningTypeProductRepository extends \Doctrine\ORM\EntityRepository
{
}
