<?php

namespace PlanningBundle\Repository;

/**
 * PlanningProductActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningProductActorRepository extends \Doctrine\ORM\EntityRepository
{
}
