<?php

namespace PlanningBundle\Repository;

/**
 * PlanningTypeProductPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningTypeProductPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
