<?php

namespace PlanningBundle\Entity\Main;

/**
 * PlanningProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningProductTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
