<?php

namespace PlanningBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findskill($id)
    {
        // Création d'une requete personnalisé Query Builder
        $q = $this->createQueryBuilder("s") // Création d'un alias
        ->select('s.id, s.position, s.name') // Selection des alias dont on a besoin
            ->where("s.id = :skillid") // En pointant vers la bonne donnée
            ->setParameter('skillid',$id)
            ->getQuery();

        return $q->getResult();
    }
}
