<?php

namespace PlanningBundle\Repository\Main;

/**
 * calendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class calendarRepository extends \Doctrine\ORM\EntityRepository
{
}
