<?php

namespace PlanningBundle\Repository\Main;

/**
 * DisponibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActorAvailibility($actor_id, $date) 
    {
        $q = $this->createQueryBuilder("d")
                ->where('d.date LIKE :date')
                ->andWhere('d.actor = :actor_id')
                ->setParameter(':date', $date .'%')
                ->setParameter(':actor_id', $actor_id)
                ->select(' sum(d.nbreHeure) as sumTask ')
                ->getQuery();
        return $q->getResult();
        
    }
}
