<?php

namespace PlanningBundle\Repository\Main;

/**
 * PlanificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlanif($idSalDoc)
    {
        // Création d'une requete personnalisé Query Builder
        $q = $this->createQueryBuilder("p")
//            ->select('sp')// Création d'un alias
            ->join('p.sousPlanif', 'sp')
            ->join('p.saleDocumentLine', 'sd')
            ->where("sd.id = :idSal") // En pointant vers la bonne donnée
            ->setParameter('idSal', $idSalDoc)
            ->getQuery();

        return $q->getSingleResult();
    }
}
