<?php

namespace PlanningBundle\Repository\Main;

/**
 * PlanificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationRepository extends \Doctrine\ORM\EntityRepository
{
}
