<?php

namespace PlanningBundle\Repository\Main;

/**
 * SousPlanificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousPlanificationRepository extends \Doctrine\ORM\EntityRepository
{
}
