<?php

namespace PlanningBundle\Repository\Main;

/**
 * TimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeRepository extends \Doctrine\ORM\EntityRepository
{
}
